name: Workflow Pkgbuilder
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      github-token:
        required: true
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Pkgbuilder
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache
          restore-keys: ${{ runner.os }}-pkgbuilder
      - name: Downloads python-pkgbuilder
        run: |
          if [ -d ~/.cache/python-pkgbuilder ]; then
            cd ~/.cache/python-pkgbuilder
            git pull
          else
            mkdir -p ~/.cache/python-pkgbuilder
            git clone https://github.com/frefolli/python-pkgbuilder ~/.cache/python-pkgbuilder
          fi
      - name: Runs python-pkgbuilder
        run: |
          python ~/.cache/python-pkgbuilder/pkgbuilder/__main__.py -v -o PKGBUILD
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.github_token }}"
          automatic_release_tag: "${{ inputs.version }}"
          prerelease: true
          title: "Latest ${{ inputs.version }} Build"
          files: |
            PKGBUILD
